# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#b69f80"

# Title color for boxes
theme[title]="#e6c93a"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#93c5b3"

# Background color of selected item in processes box
theme[selected_bg]="#22343d"

# Foreground color of selected item in processes box
theme[selected_fg]="#b69f80"

# Color of inactive/disabled text
theme[inactive_fg]="#255051"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#93c5b3"

# Box outline and divider line color
theme[cpu_box]="#63bba5"
theme[mem_box]="#63bba5"
theme[net_box]="#63bba5"
theme[proc_box]="#63bba5"
theme[div_line]="#255051"

# Gradient for all meters and graphs
theme[temp_start]="#93c5b3"
theme[temp_mid]="#e6c93a"
theme[temp_end]="#63bba5"


theme[cpu_start]="#93c5b3"
theme[cpu_mid]="#e6c93a"
theme[cpu_end]="#63bba5"


theme[free_start]="#63bba5"
theme[free_mid]="#e6c93a"
theme[free_end]="#e6c93a"


theme[cached_start]="#e6c93a"
theme[cached_mid]="#e6c93a"
theme[cached_end]="#e6c93a"


theme[available_start]="#93c5b3"
theme[available_mid]="#93c5b3"
theme[available_end]="#93c5b3"


theme[used_start]="#63bba5"
theme[used_mid]="#63bba5"
theme[used_end]="#63bba5"


theme[download_start]="#e6c93a"
theme[download_mid]="#93c5b3"
theme[download_end]="#63bba5"


theme[upload_start]="#e6c93a"
theme[upload_mid]="#93c5b3"
theme[upload_end]="#63bba5"
