-- Generated by scripts/hypr2lua.
-- Source: /home/oldjobobo/Projects/themes/omarchy-dispatch-theme/hyprland.conf

local activeBorderColor = "rgb(d8c7b0)"
local inactiveBorderColor = "rgba(8a7b68bb)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 5,
    gaps_in = 10,
    gaps_out = 20,
  },
  decoration = {
    rounding = 0,
    blur = {
      enabled = true,
      size = 8,
      passes = 2,
      noise = 0.02,
      brightness = 0.85,
      xray = false,
    },
    shadow = {
      enabled = true,
      range = 12,
      render_power = 2,
      color = "rgba(25505166)",
      color_inactive = "rgba(25505133)",
    },
  },
  animations = {
    enabled = true,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
})

hl.curve("dispatch", { type = "bezier", points = { { 0.25, 0.1 }, { 0.25, 1.0 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 3,
  bezier = "dispatch",
  style = "slide",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 2,
  bezier = "dispatch",
  style = "slide",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 3,
  bezier = "dispatch",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 4,
  bezier = "dispatch",
  style = "slide",
})
